spring.application.name=personal-blog-admin
server.port=${BLOG_SERVER_PORT:8081}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
blog.upload.friend-link-logo-dir=${BLOG_FRIEND_LINK_LOGO_DIR:uploads/friend-links}
blog.upload.avatar-dir=${BLOG_AVATAR_DIR:uploads/avatars}
blog.upload.article-cover-dir=${BLOG_ARTICLE_COVER_DIR:uploads/article-covers}
xxl.job.enabled=${XXL_JOB_ENABLED:true}
xxl.job.admin.addresses=${XXL_JOB_ADMIN_ADDRESSES:http://127.0.0.1:8088/xxl-job-admin}
xxl.job.accessToken=${XXL_JOB_ACCESS_TOKEN:default_token}
xxl.job.executor.appname=${XXL_JOB_EXECUTOR_APPNAME:blog-job-executor}
xxl.job.executor.address=${XXL_JOB_EXECUTOR_ADDRESS:}
xxl.job.executor.ip=${XXL_JOB_EXECUTOR_IP:}
xxl.job.executor.port=${XXL_JOB_EXECUTOR_PORT:9999}
xxl.job.executor.logpath=${XXL_JOB_EXECUTOR_LOGPATH:logs/xxl-job}
xxl.job.executor.logretentiondays=${XXL_JOB_EXECUTOR_LOG_RETENTION_DAYS:30}
